### ISSUE TITLE
1.20.4 Packs not overriding, stacking instead

### ISSUE THREAD

**Issue by BloonsDooms** [saicone/OneTimePack#3]
In 1.20.4 the behavior where you send the resource pack to the client was changed from overriding the existing pack, to adding another pack.

There is a new packet that can be sent to disable individual packs or all packs, could this be implemented?

**Comment by Rubenicos** [comment]
Download latest version and check the new `behavior` configuration, by default it override packs on PLAY protocol and stack on CONFIGURATION protocol.
